version: "3.9"


services:
  fastapi:
    build: ./fastapi
    ports:
      - 5000:5000
    volumes:
      - ./fastapi:/app:Z
    networks:
      - to-do-list-v2
    depends_on:
      - db
  sveltekit:
    build: ./sveltekit
    ports:
      - 3000:3000
    volumes:
      - ./sveltekit:/app:Z
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
    networks:
      - to-do-list-v2
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    env_file: .env
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - to-do-list-v2
    ports:
      - 6666:3306

networks:
  to-do-list-v2:
